apiVersion: v1
kind: Service
metadata:
  name: config-service
  labels:
    app: config-service
spec:
  ports:
  - name: config-service
    port: 8088
    protocol: TCP
    targetPort: 8088
  selector:
    app: config-service
